### ISSUE TITLE
Delete Question

### ISSUE THREAD

**Issue by JamesAnderson30** [Johney141/Stack-Flow#5]
# Delete Question

## User Functions

As a user, I should be able to delete a question I have asked.

## Tasks

- [ ] When a user clicks on a "Delete" link on any of their questions, they should be presented with a modal that confirms their decision to delete their question
- [ ] This modal should be a component that returns the link and all the javascript to make it work
- [ ] If the delete is confirmed, the user should delete their question and they should be redirected to the home page
## Bugs
